[package]
name = "tools"
version = "0.1.0"
edition = "2024"
description = "Tools for working with the Robobus protocol"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }


[dependencies.srobo_base]
git = "ssh://git@github.com/nnctroboticsclub/srobo_base.git"
features = ["std"]
